server:
  port: 8888
#  servlet:
#    path: /
spring:
  application:
    name: admin-server
  security:
    user:
      name: "admin"
      password: "admin"
  boot:
    admin:
      client:
        username: "admin"
        password: "admin"
        url: http://localhost:8080/adminserver-1.0.1
        instance:
          service-base-url: http://localhost:8080/adminserver-1.0.0


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS